# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Dynamic-Loader
version:      0.99
version_from: lib/Dynamic/Loader.pm
installdirs:  site
requires:
    Env::Path:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
